eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:8085/uaa/users/current